version: '3.8'

services:
  db:
    image: postgres:17
    container_name: agsr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AGSRTestTask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: AGSRTestTask.API/Dockerfile
    container_name: agsr-api
    ports:
      - "5134:5134"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5134
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=AGSRTestTask;User Id=postgres;Password=postgres;
    depends_on:
      - db
    restart: on-failure

  generator:
    build:
      context: .
      dockerfile: AGSRTestTask.Generator/Dockerfile
    container_name: agsr-generator
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=AGSRTestTask;User Id=postgres;Password=postgres;
    depends_on:
      - db
    restart: "no"

volumes:
  postgres_data:
